language: clang

sudo: required
dist: trusty

branches:
  except:
    - release

branches:
  only:
    - master
    - develop
    - travis

install:
  - gem install coveralls-lcov

services:
  - docker

script:
  - MAKETARGET=buildall make dbuild

after_success:
  - coveralls-lcov /home/travis/build/miracl/milagro-crypto-c/target/LINUX_64BIT_COVERAGE/coverage/amcl.info
